import { chmodSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "fs";
import { homedir } from "os";
import { delimiter, join } from "path";

const SHIM_DIR = join(homedir(), ".spinner-recruit", "bin");
const MARKER_START = "# >>> spinner-recruit shim >>>";
const MARKER_END = "# <<< spinner-recruit shim <<<";

function shimFile(tool: string): string {
  return join(SHIM_DIR, tool);
}

function rcFile(): string {
  const shell = process.env.SHELL ?? "";
  if (shell.includes("bash")) return join(homedir(), ".bash_profile");
  return join(homedir(), ".zshrc"); // zsh is the macOS default; also our best guess for unknown shells
}

// Finds the real binary on PATH, skipping our own shim directory so
// re-running install after a previous install still finds the original.
// Also used directly by index.ts to resolve `spinner-recruit <tool>` to a
// real path before handing it to tmux: without this, a user who has
// `install`ed a shim and then explicitly runs `spinner-recruit claude`
// would hand tmux the literal string "claude", which the *new* tmux pane's
// shell would resolve straight back through the shim directory on $PATH —
// nesting a whole second wrapped session (its own tmux session, its own ad
// pane) inside the first one.
export function findRealTarget(tool: string): string | null {
  const dirs = (process.env.PATH ?? "").split(delimiter);
  for (const dir of dirs) {
    if (!dir || dir === SHIM_DIR) continue;
    const candidate = join(dir, tool);
    if (existsSync(candidate)) return candidate;
  }
  return null;
}

function shimScript(realTargetPath: string): string {
  // @latest, not bare `spinner-recruit`: npx reuses whatever got cached on a
  // user's first run and never re-checks the registry for a bare package
  // name (confirmed against npm 10.9.2) — without the version tag, this shim
  // would pin every future invocation to whatever version happened to be
  // current the day it was installed, silently never picking up fixes.
  return `#!/bin/sh\n# Generated by \`spinner-recruit install\` — do not edit by hand, re-run install instead.\nexport SPINNER_RECRUIT_TARGET="${realTargetPath}"\nexec npx --yes spinner-recruit@latest "$@"\n`;
}

function rcBlock(): string {
  return `\n${MARKER_START}\nexport PATH="$HOME/.spinner-recruit/bin:$PATH"\n${MARKER_END}\n`;
}

function readRc(): string {
  try {
    return readFileSync(rcFile(), "utf8");
  } catch {
    return "";
  }
}

export function installShim(tool: string, dryRun: boolean): void {
  const realTargetPath = findRealTarget(tool);
  if (!realTargetPath) {
    console.error(
      `spinner-recruit install: couldn't find a \`${tool}\` binary on your PATH. ` +
        `Install it first, then re-run \`spinner-recruit install ${tool}\`.`,
    );
    process.exitCode = 1;
    return;
  }

  const rc = rcFile();
  const rcContent = readRc();
  const rcAlreadyPatched = rcContent.includes(MARKER_START);

  if (dryRun) {
    console.log(`Would write shim: ${shimFile(tool)}\n${shimScript(realTargetPath)}`);
    console.log(
      rcAlreadyPatched
        ? `${rc} already has the PATH line — would leave it untouched.`
        : `Would append to ${rc}:${rcBlock()}`,
    );
    return;
  }

  mkdirSync(SHIM_DIR, { recursive: true });
  writeFileSync(shimFile(tool), shimScript(realTargetPath));
  chmodSync(shimFile(tool), 0o755);

  if (!rcAlreadyPatched) writeFileSync(rc, rcContent + rcBlock());

  console.log(
    `Installed. Found your real \`${tool}\` at ${realTargetPath}.\n` +
      `Open a new terminal tab (or run \`hash -r\`, zsh/bash's command-cache reset) ` +
      `for it to take effect — \`source ${rc}\` alone won't, since your shell already ` +
      `cached \`${tool}\`'s old location before this ran.\n` +
      `From then on, \`${tool}\` in any terminal — including VS Code's integrated ` +
      "terminal — runs through spinner-recruit automatically.\n\n" +
      "Note: this can't reach VS Code's own sidebar/chat panel for this or any " +
      "other coding assistant — that UI never invokes a terminal command, so " +
      "there's no process to intercept.",
  );
}

export function uninstallShim(tool: string, dryRun: boolean): void {
  const rc = rcFile();
  const rcContent = readRc();
  const file = shimFile(tool);

  if (dryRun) {
    console.log(`Would remove: ${file}`);
    const remainingAfter = listOtherShims(tool);
    if (remainingAfter.length === 0) {
      console.log(`Would also remove the spinner-recruit block from ${rc} (no other shims left).`);
    } else {
      console.log(`Would leave ${rc}'s PATH line in place — other shims still installed: ${remainingAfter.join(", ")}`);
    }
    return;
  }

  if (existsSync(file)) rmSync(file, { force: true });

  const remaining = listOtherShims(tool);
  if (remaining.length === 0) {
    const blockPattern = new RegExp(`\\n?${MARKER_START}[\\s\\S]*?${MARKER_END}\\n?`);
    const patchedRc = rcContent.replace(blockPattern, "\n");
    if (patchedRc !== rcContent) writeFileSync(rc, patchedRc);
    console.log(`Removed the \`${tool}\` shim and the PATH line in ${rc} (no other shims left).`);
  } else {
    console.log(`Removed the \`${tool}\` shim. Left ${rc}'s PATH line in place — still shimming: ${remaining.join(", ")}`);
  }
}

function listOtherShims(excluding: string): string[] {
  try {
    return readdirSync(SHIM_DIR).filter((name) => name !== excluding);
  } catch {
    return [];
  }
}
